import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminLayout from "@/components/layouts/AdminLayout";
import AuthProvider from "@/components/layouts/AuthProvider";
import ReduxProvider from "@/components/providers/ReduxProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminRootLayout({
    children,
}) {
    return (
        <AuthProvider>
            <ReduxProvider>
                <AdminLayout>
                    {children}
                </AdminLayout>
            </ReduxProvider>
        </AuthProvider>
    );
}
